import 'package:connectivity/connectivity.dart';
import 'package:get_it/get_it.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:template/data/datasource/remote/dio/dio_client.dart';
import 'package:template/data/repository/auth_repository.dart';
import 'package:template/data/repository/bang_bang_cap_repository.dart';
import 'package:template/data/repository/bang_gia_dang_tin_repository.dart';
import 'package:template/data/repository/bang_gia_don_hang_repository.dart';
import 'package:template/data/repository/bang_gia_loc_ho_so_repository.dart';
import 'package:template/data/repository/bang_luong_repository.dart';
import 'package:template/data/repository/bao_cao_nhan_vien_repository.dart';
import 'package:template/data/repository/bao_hiem_repository.dart';
import 'package:template/data/repository/cham_cong_repository.dart';
import 'package:template/data/repository/chi_tiet_don_hang_repository.dart';
import 'package:template/data/repository/chi_tiet_vat_tu_repository.dart';
import 'package:template/data/repository/chuc_vu_repository.dart';
import 'package:template/data/repository/chuyen_mon_repository.dart';
import 'package:template/data/repository/chuyen_nganh_chinh_repository.dart';
import 'package:template/data/repository/cong_viec_nhan_vien_repository.dart';
import 'package:template/data/repository/dang_ky_bao_hiem_repository.dart';
import 'package:template/data/repository/dang_ky_hop_dong_s_b_s_repository.dart';
import 'package:template/data/repository/dang_ky_thue_repository.dart';
import 'package:template/data/repository/dang_ky_viec_moi_repository.dart';
import 'package:template/data/repository/danh_gia_dai_ly_repository.dart';
import 'package:template/data/repository/danh_muc_san_pham_repository.dart';
import 'package:template/data/repository/danh_muc_tin_tuc_repository.dart';
import 'package:template/data/repository/danh_sach_bao_gia_don_dich_vu_repository.dart';
import 'package:template/data/repository/danh_sach_tho_thau_bao_gia_repository.dart';
import 'package:template/data/repository/danh_sach_ung_tuyen_repository.dart';
import 'package:template/data/repository/dieu_khoan_chinh_sach_repository.dart';
import 'package:template/data/repository/don_dich_vu_repository.dart';
import 'package:template/data/repository/don_hang_repository.dart';
import 'package:template/data/repository/don_vi_cung_cap_repository.dart';
import 'package:template/data/repository/du_an_khach_hang_repository.dart';
import 'package:template/data/repository/du_an_nhan_vien_repository.dart';
import 'package:template/data/repository/giay_chung_nhan_suc_khoe_repository.dart';
import 'package:template/data/repository/hang_muc_xay_dung_repository.dart';
import 'package:template/data/repository/hinh_thuc_lam_viec_repository.dart';
import 'package:template/data/repository/hinh_thuc_thanh_toan_repository.dart';
import 'package:template/data/repository/hop_thu_repository.dart';
import 'package:template/data/repository/image_repository.dart';
import 'package:template/data/repository/ke_khai_kinh_nghiem_repository.dart';
import 'package:template/data/repository/kho_hang_dai_ly_repository.dart';
import 'package:template/data/repository/kho_hang_repository.dart';
import 'package:template/data/repository/lich_su_giao_dich_repository.dart';
import 'package:template/data/repository/lich_su_vi_tien_repository.dart';
import 'package:template/data/repository/lien_he_cong_ty_repository.dart';
import 'package:template/data/repository/loai_cong_viec_repository.dart';
import 'package:template/data/repository/loai_nhan_vien_repository.dart';
import 'package:template/data/repository/loai_tai_khoan_repository.dart';
import 'package:template/data/repository/loai_tot_nghiep_repository.dart';
import 'package:template/data/repository/loai_van_chuyen_repository.dart';
import 'package:template/data/repository/mat_hang_dac_trung_repository.dart';
import 'package:template/data/repository/muc_luong_du_kien_repository.dart';
import 'package:template/data/repository/ngoai_ngu_repository.dart';
import 'package:template/data/repository/nhan_vien_repository.dart';
import 'package:template/data/repository/nhap_kho_hang_dai_ly_repository.dart';
import 'package:template/data/repository/nhom_cua_hang_repository.dart';
import 'package:template/data/repository/nhom_dich_vu_repository.dart';
import 'package:template/data/repository/notifications_repository.dart';
import 'package:template/data/repository/phan_hoi_don_dich_vu_repository.dart';
import 'package:template/data/repository/phuong_xa_repository.dart';
import 'package:template/data/repository/quan_huyen_repository.dart';
import 'package:template/data/repository/quy_che_cong_ty_repository.dart';
import 'package:template/data/repository/san_pham_repository.dart';
import 'package:template/data/repository/so_nam_kinh_nghiem_repository.dart';
import 'package:template/data/repository/tai_khoan_repository.dart';
import 'package:template/data/repository/thoi_gian_lam_viec_repository.dart';
import 'package:template/data/repository/thong_bao_repository.dart';
import 'package:template/data/repository/thong_so_ky_thuat_repository.dart';
import 'package:template/data/repository/thong_tin_dang_ky_hop_dong_repository.dart';
import 'package:template/data/repository/thong_tin_f_s_s_repository.dart';
import 'package:template/data/repository/thong_tin_ngan_hang_repository.dart';
import 'package:template/data/repository/thu_chi_nhan_vien_repository.dart';
import 'package:template/data/repository/tin_hoc_repository.dart';
import 'package:template/data/repository/tin_tuc_repository.dart';
import 'package:template/data/repository/tinh_tp_repository.dart';
import 'package:template/data/repository/trang_thai_bao_gia_repository.dart';
import 'package:template/data/repository/trang_thai_don_dich_vu_repository.dart';
import 'package:template/data/repository/trang_thai_don_hang_repository.dart';
import 'package:template/data/repository/trang_thai_du_an_repository.dart';
import 'package:template/data/repository/trang_thai_thanh_toan_repository.dart';
import 'package:template/data/repository/trinh_do_hoc_van_repository.dart';
import 'package:template/data/repository/trinh_do_repository.dart';
import 'package:template/data/repository/tu_van_repository.dart';
import 'package:template/data/repository/tuyen_dung_repository.dart';
import 'package:template/data/repository/vat_tu_repository.dart';
import 'package:template/data/repository/vi_tien_repository.dart';
import 'package:template/data/repository/xuat_nhap_kho_repository.dart';
import 'package:template/helper/network_info.dart';
import 'package:template/provider/auth_provider.dart';
import 'package:template/provider/bang_bang_cap_provider.dart';
import 'package:template/provider/bang_gia_dang_tin_provider.dart';
import 'package:template/provider/bang_gia_don_hang_provider.dart';
import 'package:template/provider/bang_gia_loc_ho_so_provider.dart';
import 'package:template/provider/bang_gia_phi_van_chuyen_provider.dart';
import 'package:template/provider/bang_luong_provider.dart';
import 'package:template/provider/bao_cao_nhan_vien_provider.dart';
import 'package:template/provider/bao_hiem_provider.dart';
import 'package:template/provider/cham_cong_provider.dart';
import 'package:template/provider/chi_tiet_don_hang_provider.dart';
import 'package:template/provider/chi_tiet_vat_tu_provider.dart';
import 'package:template/provider/chuc_vu_provider.dart';
import 'package:template/provider/chuyen_mon_provider.dart';
import 'package:template/provider/chuyen_nganh_chinh_provider.dart';
import 'package:template/provider/cong_viec_nhan_vien_provider.dart';
import 'package:template/provider/dang_ky_bao_hiem_provider.dart';
import 'package:template/provider/dang_ky_hop_dong_s_b_s_provider.dart';
import 'package:template/provider/dang_ky_thue_provider.dart';
import 'package:template/provider/dang_ky_viec_moi_provider.dart';
import 'package:template/provider/danh_gia_dai_ly_provider.dart';
import 'package:template/provider/danh_muc_san_pham_provider.dart';
import 'package:template/provider/danh_muc_tin_tuc_provider.dart';
import 'package:template/provider/danh_sach_bao_gia_don_dich_vu_provider.dart';
import 'package:template/provider/danh_sach_tho_thau_bao_gia_provider.dart';
import 'package:template/provider/danh_sach_ung_tuyen_provider.dart';
import 'package:template/provider/dieu_khoan_chinh_sach_provider.dart';
import 'package:template/provider/don_dich_vu_provider.dart';
import 'package:template/provider/don_hang_provider.dart';
import 'package:template/provider/don_vi_cung_cap_provider.dart';
import 'package:template/provider/du_an_khach_hang_provider.dart';
import 'package:template/provider/du_an_nhan_vien_provider.dart';
import 'package:template/provider/giay_chung_nhan_suc_khoe_provider.dart';
import 'package:template/provider/hang_muc_xay_dung_provider.dart';
import 'package:template/provider/hinh_thuc_lam_viec_provider.dart';
import 'package:template/provider/hinh_thuc_thanh_toan_provider.dart';
import 'package:template/provider/hop_thu_provider.dart';
import 'package:template/provider/ke_khai_kinh_nghiem_provider.dart';
import 'package:template/provider/kho_hang_dai_ly_provider.dart';
import 'package:template/provider/kho_hang_provider.dart';
import 'package:template/provider/lich_su_giao_dich_provider.dart';
import 'package:template/provider/lich_su_vi_tien_provider.dart';
import 'package:template/provider/lien_he_cong_ty_provider.dart';
import 'package:template/provider/loai_cong_viec_provider.dart';
import 'package:template/provider/loai_nhan_vien_provider.dart';
import 'package:template/provider/loai_tai_khoan_provider.dart';
import 'package:template/provider/loai_tot_nghiep_provider.dart';
import 'package:template/provider/loai_van_chuyen_provider.dart';
import 'package:template/provider/mat_hang_dac_trung_provider.dart';
import 'package:template/provider/muc_luong_du_kien_provider.dart';
import 'package:template/provider/ngoai_ngu_provider.dart';
import 'package:template/provider/nhan_vien_provider.dart';
import 'package:template/provider/nhap_kho_hang_dai_ly_provider.dart';
import 'package:template/provider/nhom_cua_hang_provider.dart';
import 'package:template/provider/nhom_dich_vu_provider.dart';
import 'package:template/provider/notifications_provider.dart';
import 'package:template/provider/phan_hoi_don_dich_vu_provider.dart';
import 'package:template/provider/quan_huyen_provider.dart';
import 'package:template/provider/quy_che_cong_ty_provider.dart';
import 'package:template/provider/san_pham_provider.dart';
import 'package:template/provider/so_nam_kinh_nghiem_provider.dart';
import 'package:template/provider/tai_khoan_provider.dart';
import 'package:template/provider/thoi_gian_lam_viec_provider.dart';
import 'package:template/provider/thong_bao_provider.dart';
import 'package:template/provider/thong_so_ky_thuat_provider.dart';
import 'package:template/provider/thong_tin_dang_ky_hop_dong_provider.dart';
import 'package:template/provider/thong_tin_f_s_s_provider.dart';
import 'package:template/provider/thong_tin_ngan_hang_provider.dart';
import 'package:template/provider/thu_chi_nhan_vien_provider.dart';
import 'package:template/provider/tin_hoc_provider.dart';
import 'package:template/provider/tin_tuc_provider.dart';
import 'package:template/provider/tinh_tp_provider.dart';
import 'package:template/provider/trang_thai_bao_gia_provider.dart';
import 'package:template/provider/trang_thai_don_dich_vu_provider.dart';
import 'package:template/provider/trang_thai_don_hang_provider.dart';
import 'package:template/provider/trang_thai_du_an_provider.dart';
import 'package:template/provider/trang_thai_thanh_toan_provider.dart';
import 'package:template/provider/trinh_do_hoc_van_provider.dart';
import 'package:template/provider/trinh_do_provider.dart';
import 'package:template/provider/tu_van_provider.dart';
import 'package:template/provider/tuyen_dung_provider.dart';
import 'package:template/provider/upload_image_provider.dart';
import 'package:template/provider/vat_tu_provider.dart';
import 'package:template/provider/vi_tien_provider.dart';
import 'package:template/provider/xuat_nhap_kho_provider.dart';
import 'data/datasource/remote/dio/logging_interceptor.dart';
import 'data/repository/bang_gia_phi_van_chuyen_repository.dart';
import 'data/repository/tai_khoan_repository.dart';
import 'provider/phuong_xa_provider.dart';
import 'sharedpref/shared_preference_helper.dart';

final sl = GetIt.instance;

Future<void> init() async {
  // External
  final sharedPreferences = await SharedPreferences.getInstance();
  sl.registerSingleton<SharedPreferenceHelper>(
      SharedPreferenceHelper(sharedPreferences));
  sl.registerSingleton<LoggingInterceptor>(LoggingInterceptor());
  sl.registerLazySingleton(() => Connectivity());

  // Core
  sl.registerLazySingleton(() => NetworkInfo(sl()));
  sl.registerSingleton<DioClient>(DioClient());

  // Repository
  sl.registerLazySingleton(() => AuthRepository());
  sl.registerLazySingleton(() => BangBangCapRepository());
  sl.registerLazySingleton(() => BangGiaDangTinRepository());
  sl.registerLazySingleton(() => BangGiaDonHangRepository());
  sl.registerLazySingleton(() => BangGiaLocHoSoRepository());
  sl.registerLazySingleton(() => BangGiaPhiVanChuyenRepository());
  sl.registerLazySingleton(() => BangLuongRepository());
  sl.registerLazySingleton(() => BaoCaoNhanVienRepository());
  sl.registerLazySingleton(() => ChamCongRepository());
  sl.registerLazySingleton(() => ChiTietDonHangRepository());
  sl.registerLazySingleton(() => ChiTietVatTuRepository());
  sl.registerLazySingleton(() => ChucVuRepository());
  sl.registerLazySingleton(() => ChuyenMonRepository());
  sl.registerLazySingleton(() => ChuyenNganhChinhRepository());
  sl.registerLazySingleton(() => DangKyBaoHiemRepository());
  sl.registerLazySingleton(() => BaoHiemRepository());
  sl.registerLazySingleton(() => HangMucXayDungRepository());
  sl.registerLazySingleton(() => LoaiCongViecRepository());
  sl.registerLazySingleton(() => NhomDichVuRepository());
  sl.registerLazySingleton(() => TinhTpRepository());
  sl.registerLazySingleton(() => QuanHuyenRepository());
  sl.registerLazySingleton(() => PhuongXaRepository());
  sl.registerLazySingleton(() => TaiKhoanRepository());
  sl.registerLazySingleton(() => DonDichVuRepository());
  sl.registerLazySingleton(() => TinTucRepository());
  sl.registerLazySingleton(() => DanhMucTinTucRepository());
  sl.registerLazySingleton(() => CongViecNhanVienRepository());
  sl.registerLazySingleton(() => KhoHangRepository());
  sl.registerLazySingleton(() => ThuChiNhanVienRepository());
  sl.registerLazySingleton(() => ThongBaoRepository());
  sl.registerLazySingleton(() => SanPhamRepository());
  sl.registerLazySingleton(() => DanhMucSanPhamRepository());
  sl.registerLazySingleton(() => PhanHoiDonDichVuRepository());
  sl.registerLazySingleton(() => TrangThaiDonHangRepository());
  sl.registerLazySingleton(() => VatTuRepository());
  sl.registerLazySingleton(() => DanhSachThoThauBaoGiaRepository());
  sl.registerLazySingleton(() => DanhSachBaoGiaDonDichVuRepository());
  sl.registerLazySingleton(() => DangKyHopDongSBSRepository());
  sl.registerLazySingleton(() => DangKyThueRepository());
  sl.registerLazySingleton(() => DangKyViecMoiRepository());
  sl.registerLazySingleton(() => DanhGiaDaiLyRepository());
  sl.registerLazySingleton(() => DanhSachUngTuyenRepository());
  sl.registerLazySingleton(() => DieuKhoanChinhSachRepository());
  sl.registerLazySingleton(() => DonHangRepository());
  sl.registerLazySingleton(() => DonViCungCapRepository());
  sl.registerLazySingleton(() => DuAnKhachHangRepository());
  sl.registerLazySingleton(() => DuAnNhanVienRepository());
  sl.registerLazySingleton(() => GiayChungNhanSucKhoeRepository());
  sl.registerLazySingleton(() => HinhThucLamViecRepository());
  sl.registerLazySingleton(() => HinhThucThanhToanRepository());
  sl.registerLazySingleton(() => ImageUpdateRepository());
  sl.registerLazySingleton(() => KeKhaiKinhNghiemRepository());
  sl.registerLazySingleton(() => KhoHangDaiLyRepository());
  sl.registerLazySingleton(() => LichSuGiaoDichRepository());
  sl.registerLazySingleton(() => LienHeCongTyRepository());
  sl.registerLazySingleton(() => LoaiNhanVienRepository());
  sl.registerLazySingleton(() => LoaiTaiKhoanRepository());
  sl.registerLazySingleton(() => LoaiTotNghiepRepository());
  sl.registerLazySingleton(() => LoaiVanChuyenRepository());
  sl.registerLazySingleton(() => MatHangDacTrungRepository());
  sl.registerLazySingleton(() => MucLuongDuKienRepository());
  sl.registerLazySingleton(() => NgoaiNguRepository());
  sl.registerLazySingleton(() => NhanVienRepository());
  sl.registerLazySingleton(() => NhomCuaHangRepository());
  sl.registerLazySingleton(() => NotificationRepository());
  sl.registerLazySingleton(() => QuyCheCongTyRepository());
  sl.registerLazySingleton(() => SoNamKinhNghiemRepository());
  sl.registerLazySingleton(() => ThoiGianLamViecRepository());
  sl.registerLazySingleton(() => ThongSoKyThuatRepository());
  sl.registerLazySingleton(() => ThongTinFSSRepository());
  sl.registerLazySingleton(() => ThongTinNganHangRepository());
  sl.registerLazySingleton(() => TinHocRepository());
  sl.registerLazySingleton(() => TrangThaiBaoGiaRepository());
  sl.registerLazySingleton(() => TrangThaiDuAnRepository());
  sl.registerLazySingleton(() => TrangThaiThanhToanRepository());
  sl.registerLazySingleton(() => TrinhDoHocVanRepository());
  sl.registerLazySingleton(() => TrinhDoRepository());
  sl.registerLazySingleton(() => TuyenDungRepository());
  sl.registerLazySingleton(() => XuatNhapKhoRepository());
  sl.registerLazySingleton(() => TrangThaiDonDichVuRepository());
  sl.registerLazySingleton(() => HopThuRepository());
  sl.registerLazySingleton(() => ViTienRepository());
  sl.registerLazySingleton(() => LichSuViTienRepository());
  sl.registerLazySingleton(() => ThongTinDangKyHopDongRepository());
  sl.registerLazySingleton(() => TuVanRepository());
  sl.registerLazySingleton(() => NhapKhoHangDaiLyRepository());

  // Provider
  sl.registerLazySingleton(() => AuthProvider());
  sl.registerLazySingleton(() => TinTucProvider());
  sl.registerLazySingleton(() => DanhMucTinTucProvider());
  sl.registerLazySingleton(() => BangBangCapProvider());
  sl.registerLazySingleton(() => BangGiaDangTinProvider());
  sl.registerLazySingleton(() => BangGiaDonHangProvider());
  sl.registerLazySingleton(() => BangGiaLocHoSoProvider());
  sl.registerLazySingleton(() => BangGiaPhiVanChuyenProvider());
  sl.registerLazySingleton(() => BangLuongProvider());
  sl.registerLazySingleton(() => BaoCaoNhanVienProvider());
  sl.registerLazySingleton(() => ChamCongProvider());
  sl.registerLazySingleton(() => ChiTietDonHangProvider());
  sl.registerLazySingleton(() => ChiTietVatTuProvider());
  sl.registerLazySingleton(() => ChucVuProvider());
  sl.registerLazySingleton(() => ChuyenMonProvider());
  sl.registerLazySingleton(() => ChuyenNganhChinhProvider());
  sl.registerLazySingleton(() => CongViecNhanVienProvider());
  sl.registerLazySingleton(() => DangKyBaoHiemProvider());
  sl.registerLazySingleton(() => BaoHiemProvider());
  sl.registerLazySingleton(() => HangMucXayDungProvider());
  sl.registerLazySingleton(() => LoaiCongViecProvider());
  sl.registerLazySingleton(() => NhomDichVuProvider());
  sl.registerLazySingleton(() => TinhTpProvider());
  sl.registerLazySingleton(() => QuanHuyenProvider());
  sl.registerLazySingleton(() => PhuongXaProvider());
  sl.registerLazySingleton(() => TaiKhoanProvider());
  sl.registerLazySingleton(() => DonDichVuProvider());
  sl.registerLazySingleton(() => KhoHangProvider());
  sl.registerLazySingleton(() => ThuChiNhanVienProvider());
  sl.registerLazySingleton(() => ThongBaoProvider());
  sl.registerLazySingleton(() => SanPhamProvider());
  sl.registerLazySingleton(() => DanhMucSanPhamProvider());
  sl.registerLazySingleton(() => PhanHoiDonDichVuProvider());
  sl.registerLazySingleton(() => TrangThaiDonHangProvider());
  sl.registerLazySingleton(() => VatTuProvider());
  sl.registerLazySingleton(() => DanhSachThoThauBaoGiaProvider());
  sl.registerLazySingleton(() => DanhSachBaoGiaDonDichVuProvider());
  sl.registerLazySingleton(() => DangKyHopDongSBSProvider());
  sl.registerLazySingleton(() => DangKyThueProvider());
  sl.registerLazySingleton(() => DangKyViecMoiProvider());
  sl.registerLazySingleton(() => DanhGiaDaiLyProvider());
  sl.registerLazySingleton(() => DanhSachUngTuyenProvider());
  sl.registerLazySingleton(() => DieuKhoanChinhSachProvider());
  sl.registerLazySingleton(() => DonHangProvider());
  sl.registerLazySingleton(() => DonViCungCapProvider());
  sl.registerLazySingleton(() => DuAnKhachHangProvider());
  sl.registerLazySingleton(() => DuAnNhanVienProvider());
  sl.registerLazySingleton(() => GiayChungNhanSucKhoeProvider());
  sl.registerLazySingleton(() => HinhThucLamViecProvider());
  sl.registerLazySingleton(() => HinhThucThanhToanProvider());
  sl.registerLazySingleton(() => ImageUpdateProvider());
  sl.registerLazySingleton(() => KeKhaiKinhNghiemProvider());
  sl.registerLazySingleton(() => KhoHangDaiLyProvider());
  sl.registerLazySingleton(() => LichSuGiaoDichProvider());
  sl.registerLazySingleton(() => LienHeCongTyProvider());
  sl.registerLazySingleton(() => LoaiNhanVienProvider());
  sl.registerLazySingleton(() => LoaiTaiKhoanProvider());
  sl.registerLazySingleton(() => LoaiTotNghiepProvider());
  sl.registerLazySingleton(() => LoaiVanChuyenProvider());
  sl.registerLazySingleton(() => MatHangDacTrungProvider());
  sl.registerLazySingleton(() => MucLuongDuKienProvider());
  sl.registerLazySingleton(() => NgoaiNguProvider());
  sl.registerLazySingleton(() => NhanVienProvider());
  sl.registerLazySingleton(() => NhomCuaHangProvider());
  sl.registerLazySingleton(() => NotificationProvider());
  sl.registerLazySingleton(() => QuyCheCongTyProvider());
  sl.registerLazySingleton(() => SoNamKinhNghiemProvider());
  sl.registerLazySingleton(() => ThoiGianLamViecProvider());
  sl.registerLazySingleton(() => ThongSoKyThuatProvider());
  sl.registerLazySingleton(() => ThongTinFSSProvider());
  sl.registerLazySingleton(() => ThongTinNganHangProvider());
  sl.registerLazySingleton(() => TinHocProvider());
  sl.registerLazySingleton(() => TrangThaiBaoGiaProvider());
  sl.registerLazySingleton(() => TrangThaiDuAnProvider());
  sl.registerLazySingleton(() => TrangThaiThanhToanProvider());
  sl.registerLazySingleton(() => TrinhDoHocVanProvider());
  sl.registerLazySingleton(() => TrinhDoProvider());
  sl.registerLazySingleton(() => TuyenDungProvider());
  sl.registerLazySingleton(() => XuatNhapKhoProvider());
  sl.registerLazySingleton(() => TrangThaiDonDichVuProvider());
  sl.registerLazySingleton(() => HopThuProvider());
  sl.registerLazySingleton(() => ViTienProvider());
  sl.registerLazySingleton(() => LichSuViTienProvider());
  sl.registerLazySingleton(() => ThongTinDangKyHopDongProvider());
  sl.registerLazySingleton(() => TuVanProvider());
  sl.registerLazySingleton(() => NhapKhoHangDaiLyProvider());

}
